from django.conf.urls import url

from backmanage import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^account/$', views.account_detail, name='account'),
    url(r'^add_brand/$', views.add_brand, name='add_brand'),
    url(r'^admin_competence/$', views.admin_competence, name='admain_competence'),
    url(r'^admin_info/$', views.admin_info, name='admin_info'),
    url(r'^administrator/$', views.administrator, name='administrator'),
    url(r'^ads_list/$', views.ads_list, name='ads_list'),
    url(r'^advertising/$', views.advertising, name='advertising'),
    url(r'^amount/$', views.amount, name='amount'),
    url(r'^article_add/$', views.article_add, name='article_add'),
    url(r'^article_list/$', views.article_list, name='article_list'),
    url(r'^article_sort/$', views.article_sort, name='article_sort'),
    url(r'^brand_details/$', views.brand_details, name='brand_details'),
    url(r'^brand_manage/$', views.brand_manage, name='brand_manage'),
    url(r'^category_manage/$', views.category_manage, name='category_manage'),
    url(r'^competence/$', views.competence, name='competence'),
    # url(r'^competence/(\d+)/$', views.competence, name='competence'),
    url(r'^cover_management/$', views.cover_management, name='cover_management'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^guestbook/$', views.guestbook, name='guestbook'),
    url(r'^home/$', views.home, name='home'),
    url(r'^integration/$', views.integration, name='integration'),
    url(r'^member_grading/$', views.member_grading, name='member_grading'),
    url(r'^member_show/$', views.member_show, name='member_show'),
    url(r'^order_chart/$', views.order_chart, name='order_chart'),
    url(r'^order_detailed/$', views.order_detailed, name='order_detailed'),
    url(r'^order_handling/$', views.order_handling, name='order_handling'),
    url(r'^orderform/$', views.orderform, name='orderform'),
    url(r'^payment_configure/$', views.payment_configure, name='payment_configure'),
    url(r'^payment_details/$', views.payment_detail, name='payment_detail'),
    url(r'^payment_method/$', views.payment_method, name='payment_method'),
    url(r'^product_add/$', views.product_add, name='product_add'),
    url(r'^category_add/$', views.category_add, name='category_add'),
    url(r'^category_update/(?P<cid>\d+)/$', views.category_update, name='category_update'),
    url(r'^category_update/$', views.category_update, name='category_update'),
    url(r'^category_list/$', views.category_list, name='category_list'),
    url(r'^product_list/$', views.pruduct_list, name='product_list'),
    url(r'^refund/$', views.refund, name='refund'),
    url(r'^refund_detailed/$', views.refund_detailed, name='refund_detailed'),
    url(r'^shop_list/$', views.shop_list, name='shop_list'),
    url(r'^shopping_detailed/$', views.shopping_detailed, name='shopping_detailed'),
    url(r'^shops_audit/$', views.shops_audit, name='shops_audit'),
    url(r'^sort_ads/$', views.sort_ads, name='sort_ads'),
    url(r'^system_logs/$', views.system_logs, name='system_logs'),
    url(r'^system_section/$', views.system_section, name='system_section'),
    url(r'^systems/$', views.systems, name='systems'),
    url(r'^transaction/$', views.transaction, name='transaction'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^add_competence/$', views.add_competence, name='add_competence'),
    url(r'^add_admin/$', views.add_admin, name='add_admin'),
    url(r'^attribute_list/(?P<cid>\d+)/$', views.attribute_list, name='attribute_list'),
    # url(r'^attribute_list/$', views.attribute_list, name='attribute_list'),
    url(r'^attribute_update/$', views.attribute_update, name='attribute_update'),
    url(r'^attribute_delete/$', views.attribute_delete, name='attribute_delete'),
    url(r'^attribute_add/$', views.attribute_add, name='attribute_add'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^verficode/$', views.verficode, name='verficode'),
    url(r'^attribute_get/$', views.attribute_get, name='attribute_get'),
    url(r'^sku_add/(?P<bcid>\d+)/(?P<scid>\d+)/(?P<unique_code>\d+)/$', views.sku_add, name='sku_add'),
    url(r'^sku_add/$', views.sku_add, name='sku_add'),

]

